language: scala
jdk: oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
scala:
  - 2.12.3

jobs:
  include:
  - stage: scalafmt
    script: sbt scalafmt::test

  - stage: test
    script:
      - sbt compile test:compile
      - sbt gatling-thrift-example/gatling:test
