language: scala
jdk: oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
scala:
  - 2.12.3

services:
  - docker

script:
  - sbt gatling-thrift-example/docker:publishLocal
  - docker run -it -p 127.0.0.1:9911:9911 --rm -d micchon/gatling-thrift-example:0.4.0 bin/gatling-thrift-example
  - sbt scalafmt::test
  - sbt gatling-thrift-example/gatling:test
