language: scala
jdk: oraclejdk8
sudo: false
group: deprecated-2017Q4
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
scala:
  - 2.12.4

services:
  - docker

env:
  - VERSION=$(cat version.sbt | sed -e 's/version in ThisBuild := //g' | cut -d '"' -f2 | cut -d '"' -f1)

script:
  - sbt docker:publishLocal
  - docker run -it -p 127.0.0.1:9911:9911 --rm -d micchon/gatling-thrift-example:${VERSION} bin/gatling-thrift-example
  - docker ps -a
  - sbt scalafmt::test gatling:test
